input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  mutate {
    add_field => { "environment" => "development" }
  }
}

output {
  elasticsearch {
    hosts => ["${ELASTICSEARCH_HOSTS:http://elasticsearch:9200}"]
    index => "linkedin-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
