server:
  port: ${PORT:9040}

spring:
  application:
    name: chat-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

  datasource:
    url: ${POSTGRES_URL:}
    username: ${POSTGRES_USERNAME:}
    password: ${POSTGRES_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.time_zone: UTC

jwt:
  secret: ${JWT_SECRET:${JWT_SECRET_KEY:}}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info
